const localOptions = {
  caregiverType : [
    {
      label:"Groomer",
      value:"GROOMER"
    },
    {
      label:"Trainer",
      value:"TRAINER"
    },
    {
      label:"Vet",
      value:"VET"
    },
  ]
, days : [
    {
      label:"Monday",
      value:"MONDAY"
    },
    {
      label:"Tuesday",
      value:"TUESDAY"
    },
    {
      label:"Wednesday",
      value:"WEDNESDAY"
    },
    {
      label:"Thursday",
      value:"THURSDAY"
    },
    {
      label:"Friday",
      value:"FRIDAY"
    },
    {
      label:"Saturday",
      value:"SATURDAY"
    },
    {
      label:"Sunday",
      value:"SUNDAY"
    }
  ],
    palsHandled:[
        {
            label:"Chiens",
            value:"DOG"
        },
        {
            label:"Chat",
            value:"CAT"
        },
        {
            label:"NAC",
            value:"NAC"
        },
    ],
    homeService:[
        {
            label:"Yes",
            value:true
        },
        {
            label:"No",
            value:false
        },
    ],
    gender:[
        {
            label:"Male",
            value:true
        },
        {
            label:"Female",
            value: false
        }
    ],
    passport:[
        {
            label:"Yes",
            value:true
        },
        {
            label:"No",
            value: false
        }
    ]
}

export default localOptions;
