# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

name: 'Deploy angular app'
pool:
  vmImage: ubuntu-latest

stages:
  - stage: Deploy
    displayName: Deploy to petpals-backoffice
    jobs:
      - job: Deploy
        steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'specific'
              project: '12e6b272-e75b-4b73-aebc-da22ad6551a2'
              pipeline: '6'
              buildVersionToDownload: 'latest'
              downloadType: 'single'
              artifactName: 'petpals-backoffice'
              itemPattern: '$(APP_NAME)/$(APP_NAME)-*'
              downloadPath: '$(System.ArtifactsDirectory)'
              checkDownloadedFiles: true
          - task: ExtractFiles@1
            inputs:
              archiveFilePatterns: '$(System.ArtifactsDirectory)/$(APP_NAME)/$(APP_NAME)-*'
              destinationFolder: '$(System.ArtifactsDirectory)/app'
              cleanDestinationFolder: false
              overwriteExistingFiles: true
          - task: AzureStaticWebApp@0
            displayName: Deploy to Azure Static Web App
            inputs:
              workingDirectory: '$(System.ArtifactsDirectory)/app'
              output_location: '/front'
              app_location: 'front/browser'
              skip_app_build: true
              skip_api_build: true
              verbose: true
              azure_static_web_apps_api_token: '$(API_TOKEN)'