# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main
name: '$(Build.BuildId)'
pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.14'
  displayName: 'Install Node.js'
- script: |
    cd front
    npm install -g @angular/cli
    npm install
    ng build
  displayName: 'npm install and build'
- task: ArchiveFiles@2
  displayName: Archive build artifact
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/$(SUBFOLDER)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(APP_NAME)-$(Build.BuildId).zip'
    replaceExistingArchive: false
- task: PublishBuildArtifacts@1
  displayName: Publish build artifact
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(APP_NAME)-$(Build.BuildId).zip'
    ArtifactName: '$(APP_NAME)'
    publishLocation: 'Container'
- task: AzureStaticWebApp@0
  displayName: Deploy to Azure Static Web App
  inputs:
    workingDirectory: '$(Build.SourcesDirectory)'
    output_location: '/$(SUBFOLDER)'
    app_location: '/$(SUBFOLDER)/browser'
    skip_app_build: true
    skip_api_build: true
    verbose: true
    azure_static_web_apps_api_token: '$(API_TOKEN)'


