# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
  - main
pool:
  vmImage: ubuntu-latest

stages:
  - stage: build
    jobs:
      - job:
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.14'
            displayName: 'Install Node.js'
          - task: Npm@1
            inputs:
              command: 'custom'
              workingDir: 'petpals/'
              customCommand: 'npm install -g @angular/cli && npm install && npm run build && npm run test'
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/junit.xml'
              searchFolder: '$(Build.SourcesDirectory)/petpals'
              failTaskOnFailedTests: true
              failTaskOnFailureToPublishResults: true
              failTaskOnMissingResultsFile: true
          - task: PublishCodeCoverageResults@2
            inputs:
              summaryFileLocation: '$(Build.SourcesDirectory)/petpals/coverage/cobertura-coverage.xml'
              failIfCoverageEmpty: true
          - task: ArchiveFiles@2
            displayName: Archive build artifact
            inputs:
              rootFolderOrFile: '$(Build.SourcesDirectory)/$(SUBFOLDER)'
              includeRootFolder: true
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/petpals-backoffice-$(Build.BuildId).zip'
              replaceExistingArchive: false
          - task: PublishBuildArtifacts@1
            displayName: Publish build artifact
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/petpals-backoffice-$(Build.BuildId).zip'
              ArtifactName: 'petpals-backoffice'